import { defineField, defineType } from "sanity";

export const aboutPageSchema = defineType({
  name: "aboutPage",
  title: "About Page",
  type: "document",
  groups: [
    { name: "mandate", title: "Our Mandate" },
    { name: "mission", title: "Mission & Values" },
    { name: "objectives", title: "Objectives" },
    { name: "grants", title: "Types of Grants" },
    { name: "beyond", title: "Beyond Grants" },
    { name: "partners", title: "Partners" },
  ],
  fields: [
    defineField({
      name: "mandateBody",
      title: "Mandate Text",
      type: "text",
      rows: 14,
      group: "mandate",
      description: "Separate paragraphs with a blank line.",
    }),
    defineField({
      name: "mandateFootnote",
      title: "Mandate Footnote",
      type: "text",
      rows: 3,
      group: "mandate",
      description: "Small-print note shown under the mandate (e.g. the Kosovo* designation).",
    }),
    defineField({
      name: "missionBody",
      title: "Mission Text",
      type: "text",
      rows: 5,
      group: "mission",
    }),
    defineField({
      name: "valuesBody",
      title: "Values Statement",
      type: "text",
      rows: 5,
      group: "mission",
    }),
    defineField({
      name: "objectivesIntro",
      title: "Objectives Intro",
      type: "text",
      rows: 3,
      group: "objectives",
    }),
    defineField({
      name: "grantsCtaLabel",
      title: "Grants CTA Label",
      type: "string",
      group: "grants",
      initialValue: "Explore Grant Programmes",
    }),
    defineField({
      name: "grantsCtaUrl",
      title: "Grants CTA URL",
      type: "string",
      group: "grants",
      description: "Internal path (/programs) or full external URL.",
      initialValue: "/programs",
    }),
    defineField({
      name: "beyondGrantsIntro",
      title: "Beyond Grants Intro",
      type: "text",
      rows: 4,
      group: "beyond",
    }),
    defineField({
      name: "beyondGrantsItems",
      title: "Beyond Grants Topics",
      type: "array",
      of: [{ type: "string" }],
      group: "beyond",
      description: "Topics shown as visual badges (e.g. Equality, Human Rights…).",
    }),
    defineField({
      name: "partnersIntro",
      title: "Partners Intro",
      type: "text",
      rows: 3,
      group: "partners",
    }),
    defineField({
      name: "partnersCtaLabel",
      title: "Partners CTA Label",
      type: "string",
      group: "partners",
      initialValue: "Find out more about our Partners",
    }),
    defineField({
      name: "partnersCtaUrl",
      title: "Partners CTA URL",
      type: "string",
      group: "partners",
      description: "Internal path (/about/donors-partners) or full external URL.",
      initialValue: "/about/donors-partners",
    }),
  ],
  preview: { prepare: () => ({ title: "About Page" }) },
});
